### ISSUE TITLE
New tip does not contain ... warning message

### ISSUE THREAD

**Issue by YorkZ** [rcls/crap#13]
After an incremental import, I always get this warning message:

warning: Not updating refs/tags/TAG_NAME (new tip d2b66baaf49921267e9fcd25bff3f13dd4f6c27d does not contain 0af95a69da66bc184f096c90af2d7a845a3e3ee4)

What does this mean?

**Comment by rcls** [comment]
See the FAQ "I did an incremental import and got an error from git-fast-import:" in the [readme](https://github.com/rcls/crap/blob/master/README.md).
For some reason, the git history I reconstruct from the CVS repo has changed (it is the equivalent of a non-fast-foward git pull or push).

Use the --force flag to override the warning.
You may want sanity check to see what is going on; e.g., do
```
git diff --stat 0af95a69 d2b66baa
```
and check that the content of the tag is not getting corrupted.

**Comment by YorkZ** [comment]
Thank you very much for your quick response. `git diff --stat 0af95a69 d2b66baa` generated no output for me. So am I safe if I don't re-import the repository using the `--force` option? If possible, I really don't want to do it again.

**Comment by rcls** [comment]
In this case, it should be safe to either ignore the warning, or else to do an (incremental) import with --force.
The warning actually comes from the git-fast-import program (which crap-clone uses to write the git repo).
Reading the docs for git-fast-import, I believe that the consequence of the warning is that the specific ref in question is not updated, but other branches do get updated.
If you ever get this warning for a branch that people are actually commiting to, then you will want to use --force (otherwise you will not get the new commits).
As a matter of interest, how long does the import take for you? Approximately how many files and commits are there?

**Comment by YorkZ** [comment]
Thanks again for your help.

I can't remember exactly how long it took me to import the CVS projects, probably one or two hours I guess. Not sure exactly how many files, but there are more than 20 projects having development history from 2010. I should say the speed is very good. Great job!
